### PR TITLE
[WORK IN PROGRESS] fix for Jekyll 3.2+

### LINKED ISSUE #37: Error on 'jekyll build' after adding and configuring the plugin
Added and configured the plugin as described in the README. I get this error when running `bundle exec jekyll build` afterwards.

```
Configuration file: /home/jf/search-test/_config.yml
            Source: /home/jf/search-test
       Destination: /home/jf/search-test/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll_pages_api_search: checking for Node.js: v6.7.0
  Liquid Exception: undefined method `start_with?' for nil:NilClass in index.html
jekyll 3.2.1 | Error:  undefined method `start_with?' for nil:NilClass
```

Jekyll 3.2.1
Ruby 2.3.1
Node.js 6.7.0

Minimal test case here, it is a fresh Jekyll site with the jekyll_pages_api_search plugin installed: https://github.com/jfredrickson5/search-test

Site builds and renders normally if I remove the plugin from `_config.yml`.

### PR DESCRIPTION
**Pull request by afeld**
Fixes https://github.com/18F/jekyll_pages_api_search/issues/37. Also fixes the `endpoint` configuration option, which I'm not convinced was working before.

* [ ] Get tests passing
* [ ] Add tests around the `endpoint`
* [ ] Split to multiple pull requests?

### CODE REVIEW

**Comment by wslack** [comment]
@afeld random question cc @gemfarmer; we think search is still working on 18f.gsa.gov despite that being built (we think) in 3.3 - are you sure it needs work to function on future Jekyll versions?

**Comment by afeld** [comment]
Honestly, I'm not sure. Been awhile since I touched this.
